// generated_bridge.dart
// This file is auto-generated by:
// dart run flutter_rust_bridge:build

// Contains:
// - Dart wrappers for Rust functions
// - Async FFI bindings
// - Type mappings (String → RustString, etc.)

// DO NOT EDIT MANUALLY