// GENERATED CODE - DO NOT MODIFY BY HAND

/// Rust Bridge for Sprout Compiler
/// This file is auto-generated by flutter_rust_bridge_codegen

import 'dart:ffi';
import 'package:ffi/ffi.dart';

class SproutCompiler {
  final DynamicLibrary _lib;

  SproutCompiler(this._lib);

  // Security: Compile SproutScript to WASM
  String compileSproutScript(String sourceCode) {
    final sourcePtr = sourceCode.toNativeUtf8();
    final resultPtr = _compileSproutScriptPtr(sourcePtr);
    final result = resultPtr.toDartString();
    calloc.free(sourcePtr);
    return result;
  }

  // Security: Parse SproutScript to AST
  String parseSproutScript(String sourceCode) {
    final sourcePtr = sourceCode.toNativeUtf8();
    final resultPtr = _parseSproutScriptPtr(sourcePtr);
    final result = resultPtr.toDartString();
    calloc.free(sourcePtr);
    return result;
  }

  // Security: Validate code for security issues
  bool validateCode(String sourceCode) {
    final sourcePtr = sourceCode.toNativeUtf8();
    final result = _validateCodePtr(sourcePtr);
    calloc.free(sourcePtr);
    return result != 0;
  }

  // Security: Get error messages
  String getLastError() {
    final resultPtr = _getLastErrorPtr();
    final result = resultPtr.toDartString();
    return result;
  }

  // Security: Get version info
  String getVersion() {
    final resultPtr = _getVersionPtr();
    final result = resultPtr.toDartString();
    return result;
  }

  // FFI Functions
  late final _compileSproutScriptPtr = _lib
      .lookup<NativeFunction<Pointer<Utf8> Function(Pointer<Utf8>)>>(
          'compile_sprout_script')
      .asFunction<Pointer<Utf8> Function(Pointer<Utf8>)>();
  
  late final _parseSproutScriptPtr = _lib
      .lookup<NativeFunction<Pointer<Utf8> Function(Pointer<Utf8>)>>(
          'parse_sprout_script')
      .asFunction<Pointer<Utf8> Function(Pointer<Utf8>)>();
  
  late final _validateCodePtr = _lib
      .lookup<NativeFunction<Int8 Function(Pointer<Utf8>)>>(
          'validate_code')
      .asFunction<int Function(Pointer<Utf8>)>();
  
  late final _getLastErrorPtr = _lib
      .lookup<NativeFunction<Pointer<Utf8> Function()>>(
          'get_last_error')
      .asFunction<Pointer<Utf8> Function()>();
  
  late final _getVersionPtr = _lib
      .lookup<NativeFunction<Pointer<Utf8> Function()>>(
          'get_version')
      .asFunction<Pointer<Utf8> Function()>();
}

// Security: Singleton instance
SproutCompiler? _compilerInstance;

SproutCompiler getCompiler() {
  _compilerInstance ??= SproutCompiler(
    DynamicLibrary.open('libsprout_compiler.so')
  );
  return _compilerInstance!;
}

// Security: Initialize compiler with security checks
void initializeCompiler() {
  try {
    final compiler = getCompiler();
    final version = compiler.getVersion();
    print('Sprout Compiler initialized: $version');
  } catch (e) {
    print('Failed to initialize Sprout Compiler: $e');
    rethrow;
  }
}

// Security: Dispose compiler resources
void disposeCompiler() {
  // Clean up FFI resources if needed
  _compilerInstance = null;
}
