# Security: Podfile for Sprout iOS App
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# Security: Prevent CocoaPods from generating a Podfile.lock
install! 'cocoapods', :deterministic_uuids => false

# Security: Use dynamic frameworks
use_frameworks! :linkage => :static

target 'Runner' do
  use_frameworks!
  
  # Security: Flutter Pod
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Security: Biometric authentication
  pod 'LocalAuthentication', '~> 0.2'
  
  # Security: Keychain access
  pod 'KeychainAccess', '~> 4.2'
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Security: Set minimum iOS version
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
      # Security: Enable code signing
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'YES'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
      
      # Security: Enable hardening
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['OTHER_CFLAGS'] = '$(inherited) -fembed-bitcode'
      
      # Security: Enable strict checks
      config.build_settings['GCC_WARN_UNINITIALIZED_AUTOS'] = 'YES_AGGRESSIVE'
      config.build_settings['GCC_WARN_UNUSED_VARIABLE'] = 'YES'
    end
  end
end