// bindings/flutter_rust_bridge_gen.dart
// Auto-generated by `flutter_rust_bridge`
// Run: `dart run flutter_rust_bridge:build`
//
// Contains:
// - Dart ↔ Rust FFI bindings
// - Async wrappers
// - Type mappings
//
// Do not edit manually.