name: Build & Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-linux-android
          override: true

      - name: Install cargo-ndk
        run: |
          cargo install cargo-ndk
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build Rust Bridge
        working-directory: ./flutter
        run: |
          dart pub global activate flutter_rust_bridge
          dart run flutter_rust_bridge:build

      - name: Flutter Packages Get
        working-directory: ./flutter
        run: flutter pub get

      - name: Run Analysis
        working-directory: ./flutter
        run: flutter analyze
        env:
          FLUTTER_ROOT: /opt/hostedtoolcache/flutter/3.19.0-stable/x64

      - name: Run Tests
        working-directory: ./flutter
        run: flutter test

      - name: Build Android APK
        working-directory: ./flutter
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: flutter/build/app/outputs/flutter-apk/app-release.apk

      - name: Success
        run: echo "✅ Build successful! APK ready."